const SELECT_CHAT = 'SELECT_CHAT';
const LOAD_CHATS = 'LOAD_CHATS';
const MESSAGE_HISTORY = 'MESSAGE_HISTORY';
const ADD_MESSAGE = 'ADD_MESSAGE';

export {SELECT_CHAT, MESSAGE_HISTORY, LOAD_CHATS, ADD_MESSAGE}