const SELECT_CHAT = 'SELECT_CHAT';
const LOAD_CHATS = 'LOAD_CHATS';
const MESSAGE_HISTORY = 'MESSAGE_HISTORY';
const ADD_MESSAGE = 'ADD_MESSAGE';
const SEARCH_CHAT = 'SEARCH_CHAT';
const OPEN_SIDEBAR = 'OPEN_SIDEBAR';
const SIGN_IN = 'SIGN_IN';
const SIGN_OUT = 'SIGN_OUT';
const HAD_PLAYED = 'HAD_PLAYED';

export {SELECT_CHAT, MESSAGE_HISTORY, LOAD_CHATS, ADD_MESSAGE, SEARCH_CHAT, OPEN_SIDEBAR, SIGN_OUT, SIGN_IN, HAD_PLAYED}